[project]
id = "boom"
version = "0.1.0"
src = "src"
dep = "dep"
target = "native"
out   = "out/{target}/{profile}/bin/{name}{ext}"
obj   = "out/{target}/{profile}/obj"
ir    = "out/{target}/{profile}/ir"
asm   = "out/{target}/{profile}/asm"
tests = "out/{target}/{profile}/test/{name}"
module = "lib/boom.mach"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows]
isa = "x86_64"
os  = "windows"
abi = "win64"
ext = ".exe"

[target.darwin]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[lib.boom]
entry = "lib/boom.mach"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[deps.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"

[deps.mach-glfw]
git = "https://github.com/briar-systems/mach-glfw"
ref = "branch/main"

[deps.mach-gl]
git = "https://github.com/briar-systems/mach-gl"
ref = "branch/dev"

[deps.mach-vk]
git = "https://github.com/briar-systems/mach-vk"
ref = "branch/main"

[deps.mach-audio]
git = "https://github.com/briar-systems/mach-audio"
ref = "branch/dev"

[deps.mach-image]
git = "https://github.com/briar-systems/mach-image"
ref = "branch/dev"

[deps.mach-font]
git = "https://github.com/briar-systems/mach-font"
ref = "branch/dev"

[deps.mach-gltf]
git = "https://github.com/briar-systems/mach-gltf"
ref = "branch/dev"

[deps.mach-phys]
git = "https://github.com/briar-systems/mach-phys"
ref = "branch/main"

[deps.blit]
git = "https://github.com/briar-systems/blit"
ref = "branch/main"
