[project]
id      = "shaders"
version = "0.1.0"
src     = "src"
out     = "out"

[target.spirv]
isa = "spirv"
os  = "freestanding"
abi = "spirv"
of  = "spv"

[profile.debug]
opt   = 0
debug = false
simd  = "scalarize"

[profile.release]
opt   = 2
debug = false
simd  = "scalarize"

[artifact.lit_frag]
kind    = "bin"
entry   = "lit_frag.mach"
out     = "lit_frag.spv"
targets = ["spirv"]
link    = []
need    = []

[artifact.mesh_vert]
kind    = "bin"
entry   = "mesh_vert.mach"
out     = "mesh_vert.spv"
targets = ["spirv"]
link    = []
need    = []

["spirv"]
link    = []
need    = []

["spirv"]
link    = []
need    = []

[artifact.skinned_vert]
kind    = "bin"
entry   = "skinned_vert.mach"
out     = "skinned_vert.spv"
targets = ["spirv"]
link    = []
need    = []

[dep.mach-shader]
git = "https://github.com/briar-systems/mach-shader"
ref = "branch/main"

[artifact.ui_vert]
kind    = "bin"
entry   = "ui_vert.mach"
out     = "ui_vert.spv"
targets = ["spirv"]
link    = []
need    = []

[artifact.ui_frag]
kind    = "bin"
entry   = "ui_frag.mach"
out     = "ui_frag.spv"
targets = ["spirv"]
link    = []
need    = []
