[project]
id = "animation"
version = "0.2.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[profile.debug]
opt = 0
debug = true
simd = "scalarize"

[profile.release]
opt = 2
debug = false
simd = "scalarize"

[artifact.animation]
kind = "bin"
entry = "main.mach"
out = "bin/animation"
targets = ["*"]
link = []
need = []

[dep.boom]
git = "https://github.com/briar-systems/boom"
ref = "branch/dev"

[dep.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"

[dep.mach-glfw]
git = "https://github.com/briar-systems/mach-glfw"
ref = "branch/main"

[dep.mach-gl]
git = "https://github.com/briar-systems/mach-gl"
ref = "branch/dev"

[dep.mach-image]
git = "https://github.com/briar-systems/mach-image"
ref = "branch/dev"

[dep.mach-gltf]
git = "https://github.com/briar-systems/mach-gltf"
ref = "branch/dev"
